"""Embed the already-distributed local login material and public server pins.

Never supply a remote server private key. Input is the verified launcher payload.
"""
import argparse, base64, hashlib, json
from pathlib import Path

p=argparse.ArgumentParser(); p.add_argument('payload',type=Path); args=p.parse_args()
root=Path(__file__).resolve().parents[1]
manifest=json.loads((args.payload/'files.json').read_text(encoding='utf-8-sig'))
names=['launcher-certificates/online/'+x for x in ['origin.crt','login.crt','login.key']]
names += ['launcher-certificates/'+realm+'/origin.crt' for realm in ['realm2','realm3']]
values={}
for name in names:
    data=(args.payload/name).read_bytes()
    assert hashlib.sha256(data).hexdigest()==manifest[name], 'Certificate input hash mismatch'
    assert name.endswith('login.key') or b'PRIVATE KEY' not in data
    values[name]=base64.b64encode(data).decode('ascii')
header='// Generated by tools/Embed-LauncherCertificates.py. Local compatibility key is already distributed; no server private key.\n'
(root/'launcher/launcher-flutter/lib/embedded_certificates.dart').write_text(header+'const embeddedCertificates = <String, String>'+json.dumps(values,indent=2)+';\n',encoding='utf-8')
go='//go:build windows\n\n'+header+'package bridge\n\nvar embeddedCertificates = map[string]string{\n'
go+=''.join(json.dumps(k)+': '+json.dumps(v)+',\n' for k,v in values.items())+'}\n'
(root/'server/go-server/internal/bridge/embedded_certificates_windows.go').write_text(go,encoding='utf-8')
print('Embedded matching certificate entries:',len(values))
